In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 60)
pd.set_option('display.max_rows', 100)

In [39]:
path_list_scenario = "data/pangeo-cmip6.csv"

In [53]:
scenario = pd.read_csv(path_list_scenario)

In [54]:
activities = ["CMIP", "ScenarioMIP"]
experiments = ["historical", "ssp370", "ssp585"]
tables = ["Amon", "Omon"]
variables = ["hurs", "psl", "ta", "tos"]

In [55]:
scenario_filter = scenario[
    scenario["activity_id"].isin(activities) &
    scenario["experiment_id"].isin(experiments) &
    scenario["table_id"].isin(tables) &
    scenario["variable_id"].isin(variables) &
    (scenario["grid_label"] == "gn")
]

In [57]:
scenario_filter

,activity_id,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,zstore,dcpp_init_year,version
990,CMIP,NOAA-GFDL,GFDL-ESM4,historical,r3i1p1f1,Omon,tos,gn,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-ESM4/hist...,NaN,20180701
1024,CMIP,NOAA-GFDL,GFDL-ESM4,historical,r2i1p1f1,Omon,tos,gn,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-ESM4/hist...,NaN,20180701
9970,CMIP,NOAA-GFDL,GFDL-CM4,historical,r1i1p1f1,Omon,tos,gn,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-CM4/histo...,NaN,20180701
12068,ScenarioMIP,NOAA-GFDL,GFDL-ESM4,ssp585,r1i1p1f1,Omon,tos,gn,gs://cmip6/CMIP6/ScenarioMIP/NOAA-GFDL/GFDL-ES...,NaN,20180701
13298,ScenarioMIP,NOAA-GFDL,GFDL-ESM4,ssp370,r1i1p1f1,Omon,tos,gn,gs://cmip6/CMIP6/ScenarioMIP/NOAA-GFDL/GFDL-ES...,NaN,20180701
...,...,...,...,...,...,...,...,...,...,...,...
514751,CMIP,CMCC,CMCC-CM2-SR5,historical,r3i1p2f1,Amon,psl,gn,gs://cmip6/CMIP6/CMIP/CMCC/CMCC-CM2-SR5/histor...,NaN,20211108
514766,CMIP,CMCC,CMCC-CM2-SR5,historical,r2i1p2f1,Amon,ta,gn,gs://cmip6/CMIP6/CMIP/CMCC/CMCC-CM2-SR5/histor...,NaN,20211109
514768,CMIP,CMCC,CMCC-CM2-SR5,historical,r2i1p2f1,Amon,psl,gn,gs://cmip6/CMIP6/CMIP/CMCC/CMCC-CM2-SR5/histor...,NaN,20211109
514790,ScenarioMIP,MOHC,UKESM1-0-LL,ssp585,r4i1p1f2,Amon,psl,gn,gs://cmip6/CMIP6/ScenarioMIP/MOHC/UKESM1-0-LL/...,NaN,20211201
514799,ScenarioMIP,MOHC,UKESM1-0-LL,ssp585,r4i1p1f2,Amon,ta,gn,gs://cmip6/CMIP6/ScenarioMIP/MOHC/UKESM1-0-LL/...,NaN,20211201

In [ ]:
scenario_filter["Nb_source_member_diff"] = scenario_filter.groupby(["source_id", "member_id"])["activity_id"].transform(lambda x: x.size)

/tmp/ipykernel_20771/310192825.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  scenario_filter["Nb_source_member_diff"] = scenario_filter.groupby(["source_id", "member_id"])["activity_id"].transform(lambda x: x.size)

In [80]:
scenario_filter = scenario_filter[scenario_filter["Nb_source_member_diff"] == 12].reset_index(drop=True).drop(columns=["Nb_source_member_diff"])

In [84]:
scenario_filter.to_excel("data/pangeo-cmip6-filtered.xlsx", index=False)

In [87]:
scenario_filter.member_id.value_counts()

member_id
r1i1p1f1     156
r2i1p1f1      84
r3i1p1f1      72
r4i1p1f1      36
r10i1p1f1     36
r1i1p1f2      24
r11i1p1f1     24
r1i1p2f1      24
r2i1p2f1      24
r6i1p1f1      24
r2i1p1f2      24
r7i1p1f1      24
r5i1p1f1      24
r8i1p1f1      24
r3i1p2f1      24
r9i1p1f1      24
r3i1p1f2      24
r4i1p1f2      24
r8i1p1f2      24
r12i1p1f1     12
r22i1p1f1     12
r22i1p2f1     12
r17i1p2f1     12
r12i1p2f1     12
r17i1p1f1     12
r16i1p1f1     12
r11i1p2f1     12
r10i1p2f1     12
r14i1p1f1     12
r13i1p2f1     12
r16i1p2f1     12
r13i1p1f1     12
r18i1p2f1     12
r19i1p1f1     12
r21i1p2f1     12
r20i1p1f1     12
r23i1p2f1     12
r23i1p1f1     12
r18i1p1f1     12
r20i1p2f1     12
r21i1p1f1     12
r8i1p2f1      12
r7i1p2f1      12
r5i1p2f1      12
r4i1p2f1      12
r9i1p2f1      12
r19i1p2f1     12
r25i1p2f1     12
r15i1p2f1     12
r6i1p2f1      12
r15i1p1f1     12
r14i1p2f1     12
r25i1p1f1     12
r24i1p2f1     12
r24i1p1f1     12
r3i1p3f1      12
r1i1p3f1      12
r2i1p3f1      12
r4i1p3f1      12
r1i1p5f1      12
r9i1p1f2      12
r6i1p1f2      12
r10i1p1f2     12
r5i1p1f2      12
Name: count, dtype: int64

In [58]:
scenario["Scenario_exist"] = (
    scenario
    .groupby("source_id")["experiment_id"]
    .transform(lambda x: experiments.issubset(set(x)))
)

scenario["Table_exist"] = (
    scenario
    .groupby("source_id")["table_id"]
    .transform(lambda x: tables.issubset(set(x)))
)

scenario["Variable_exist"] = (
    scenario
    .groupby("source_id")["variable_id"]
    .transform(lambda x: variables.issubset(set(x)))
)

AttributeError: 'list' object has no attribute 'issubset'

In [31]:
scenario.head()

,activity_id,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,zstore,dcpp_init_year,version,Scenario_exist,Table_exist,Variable_exist
514,CMIP,NOAA-GFDL,GFDL-CM4,historical,r1i1p1f1,AERmon,emidust,gr1,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-CM4/histo...,NaN,20180301,True,True,True
515,CMIP,NOAA-GFDL,GFDL-CM4,historical,r1i1p1f1,AERmon,emiss,gr1,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-CM4/histo...,NaN,20180301,True,True,True
516,CMIP,NOAA-GFDL,GFDL-CM4,historical,r1i1p1f1,AERmon,mmrbc,gr1,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-CM4/histo...,NaN,20180301,True,True,True
517,CMIP,NOAA-GFDL,GFDL-CM4,historical,r1i1p1f1,AERmon,mmrdust,gr1,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-CM4/histo...,NaN,20180301,True,True,True
518,CMIP,NOAA-GFDL,GFDL-CM4,historical,r1i1p1f1,AERmon,mmroa,gr1,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-CM4/histo...,NaN,20180301,True,True,True

In [35]:
scenario = scenario[scenario["activity_id"].isin(activities) & scenario["Scenario_exist"] & scenario["Table_exist"] & scenario["Variable_exist"] & (scenario["grid_label"]=="gn")]

In [36]:
scenario

,activity_id,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,zstore,dcpp_init_year,version,Scenario_exist,Table_exist,Variable_exist
958,CMIP,NOAA-GFDL,GFDL-ESM4,historical,r3i1p1f1,Omon,zos,gn,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-ESM4/hist...,NaN,20180701,True,True,True
960,CMIP,NOAA-GFDL,GFDL-ESM4,historical,r3i1p1f1,SImon,siconc,gn,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-ESM4/hist...,NaN,20180701,True,True,True
970,CMIP,NOAA-GFDL,GFDL-ESM4,historical,r2i1p1f1,Omon,zos,gn,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-ESM4/hist...,NaN,20180701,True,True,True
972,CMIP,NOAA-GFDL,GFDL-ESM4,historical,r2i1p1f1,SImon,siconc,gn,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-ESM4/hist...,NaN,20180701,True,True,True
980,CMIP,NOAA-GFDL,GFDL-ESM4,historical,r3i1p1f1,Omon,wfo,gn,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-ESM4/hist...,NaN,20180701,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514797,ScenarioMIP,MOHC,UKESM1-0-LL,ssp585,r4i1p1f2,Amon,tauv,gn,gs://cmip6/CMIP6/ScenarioMIP/MOHC/UKESM1-0-LL/...,NaN,20211201,True,True,True
514798,ScenarioMIP,MOHC,UKESM1-0-LL,ssp585,r4i1p1f2,Amon,tauu,gn,gs://cmip6/CMIP6/ScenarioMIP/MOHC/UKESM1-0-LL/...,NaN,20211201,True,True,True
514799,ScenarioMIP,MOHC,UKESM1-0-LL,ssp585,r4i1p1f2,Amon,ta,gn,gs://cmip6/CMIP6/ScenarioMIP/MOHC/UKESM1-0-LL/...,NaN,20211201,True,True,True
514800,ScenarioMIP,MOHC,UKESM1-0-LL,ssp585,r4i1p1f2,Amon,cli,gn,gs://cmip6/CMIP6/ScenarioMIP/MOHC/UKESM1-0-LL/...,NaN,20211201,True,True,True
514801,ScenarioMIP,MOHC,UKESM1-0-LL,ssp585,r4i1p1f2,Amon,vas,gn,gs://cmip6/CMIP6/ScenarioMIP/MOHC/UKESM1-0-LL/...,NaN,20211201,True,True,True

In [ ]:

scenario[scenario["experiment_id"] .isin(experiments)]

In [ ]:
{"Amon": ["hurs", "psl", "ta", ], "Omon": ["tos"]}